### ISSUE TITLE
Operators panic and do not cleanup if resources are deleted

### ISSUE THREAD

**Issue by dvob** [zitadel/zitadel#2574]
**Describe the bug**
I tried to setup Zitadel for testing purposes on a local kind cluster. After starting the cluster I started the operators with `zitadel takeoff` and created the database and the zitadel resource. Then i recognized that the database does not start because I don't have a storageclass `fast`. I removed the zitadel and the database resource and then both operators panicked. After they came up again they did not remove the resources they created (cockroachdb statefulset, namespace caos-zitadel, ...). 

This is probably because ReadCrd does return nil if the resource does not exist anymore: https://github.com/caos/zitadel/blob/686c0edb5cea7aa025a0ed0ba4188d759db63bac/operator/api/database/api.go#L23

** database operator log**
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x21a9c5b]

goroutine 298 [running]:
github.com/caos/zitadel/operator/database/kinds/orb.ParseDesiredV0(0x0, 0xc000bab900, 0xc000abda70, 0x4)
	/go/src/github.com/caos/zitadel/operator/database/kinds/orb/desired.go:30 +0x3b
github.com/caos/zitadel/operator/database/kinds/orb.AdaptFunc.func1(0xc000abd4a0, 0x2b48328, 0x2b48328, 0x2b48320, 0x2b48330, 0x0, 0x0, 0xc0009774a0, 0x0, 0x0, ...)
	/go/src/github.com/caos/zitadel/operator/database/kinds/orb/adapt.go:57 +0x28d
github.com/caos/zitadel/operator/crtlcrd/database.(*Reconciler).Reconcile(0xc00044c180, 0x2de0458, 0xc000abd470, 0xc00024dbd0, 0xb, 0xc00024dbb8, 0x8, 0xc000abd400, 0x0, 0x0, ...)
	/go/src/github.com/caos/zitadel/operator/crtlcrd/database/database.go:44 +0x4ff
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0xc00021d360, 0x2de0458, 0xc000abd440, 0xc00024dbd0, 0xb, 0xc00024dbb8, 0x8, 0xc000abd400, 0x0, 0x0, ...)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.2/pkg/internal/controller/controller.go:114 +0x247
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc00021d360, 0x2de03b0, 0xc00038e080, 0x26f41e0, 0xc0009767c0)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.2/pkg/internal/controller/controller.go:311 +0x305
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc00021d360, 0x2de03b0, 0xc00038e080, 0xc0000a2000)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.2/pkg/internal/controller/controller.go:266 +0x205
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2(0xc00024c9e0, 0xc00021d360, 0x2de03b0, 0xc00038e080)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.2/pkg/internal/controller/controller.go:227 +0x6b
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.2/pkg/internal/controller/controller.go:223 +0x425
```
** zitadel operator log**
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x21a9c5b]

goroutine 297 [running]:
github.com/caos/zitadel/operator/database/kinds/orb.ParseDesiredV0(0x0, 0xc000ccac50, 0xc0002b50e0, 0x4)
	/go/src/github.com/caos/zitadel/operator/database/kinds/orb/desired.go:30 +0x3b
github.com/caos/zitadel/operator/database/kinds/orb.AdaptFunc.func1(0xc0006a0ba0, 0x2b48328, 0x2b48328, 0x2b48320, 0x2b48330, 0x0, 0x0, 0xc000346ae0, 0x0, 0x0, ...)
	/go/src/github.com/caos/zitadel/operator/database/kinds/orb/adapt.go:57 +0x28d
github.com/caos/zitadel/pkg/databases.listUsers(0xc0006a0ba0, 0x2b48328, 0x2b48328, 0x2b48320, 0x2b48330, 0x0, 0x2e1bae8, 0xc0000fe380, 0x0, 0x2a4f354, ...)
	/go/src/github.com/caos/zitadel/pkg/databases/user.go:47 +0xef
github.com/caos/zitadel/pkg/databases.CrdListUsers(0xc0006a0ba0, 0x2b48328, 0x2b48328, 0x2b48320, 0x2b48330, 0x0, 0x2e1bae8, 0xc0000fe380, 0x12, 0xc0004d1493, ...)
	/go/src/github.com/caos/zitadel/pkg/databases/user.go:23 +0x132
github.com/caos/zitadel/operator/zitadel/kinds/iam/zitadel/database.(*CrdClient).ListUsers(0xc0006a0c90, 0xc0006a0ba0, 0x2b48328, 0x2b48328, 0x2b48320, 0x2b48330, 0x0, 0x2e1bae8, 0xc0000fe380, 0x2a4f354, ...)
	/go/src/github.com/caos/zitadel/operator/zitadel/kinds/iam/zitadel/database/user.go:52 +0x66
github.com/caos/zitadel/operator/zitadel/kinds/iam/zitadel/database.AdaptFunc.func1(0x2e1bae8, 0xc0000fe380, 0xc0009813e0, 0x3ed3530, 0x2b48330, 0x0)
	/go/src/github.com/caos/zitadel/operator/zitadel/kinds/iam/zitadel/database/adapt.go:24 +0x18c
github.com/caos/zitadel/operator.QueriersToEnsureFunc(0xc0006a0ba0, 0x2b48328, 0x2b48328, 0x2b48320, 0x2b48330, 0x0, 0x7f00b5896501, 0xc000626270, 0x3, 0x3, ...)
	/go/src/github.com/caos/zitadel/operator/adapt.go:87 +0x112
github.com/caos/zitadel/operator/zitadel/kinds/iam/zitadel.AdaptFunc.func1.1.1(0x2e1bae8, 0xc0000fe380, 0xc0009813e0, 0xc000700aa0, 0x2b48330, 0x0)
	/go/src/github.com/caos/zitadel/operator/zitadel/kinds/iam/zitadel/adapt.go:246 +0xc5
github.com/caos/zitadel/operator/zitadel/kinds/iam/zitadel.AdaptFunc.func1.2(0x2e1bae8, 0xc0000fe380, 0xc0009813e0, 0x3ed3530, 0x2b48330, 0x0)
	/go/src/github.com/caos/zitadel/operator/zitadel/kinds/iam/zitadel/adapt.go:273 +0x313
github.com/caos/zitadel/operator.QueriersToEnsureFunc(0xc0006a0f60, 0x2b48328, 0x2b48328, 0x2b48320, 0x2b48330, 0x0, 0x1, 0xc000b8a3c0, 0xc, 0xc, ...)
	/go/src/github.com/caos/zitadel/operator/adapt.go:87 +0x112
github.com/caos/zitadel/operator/zitadel/kinds/iam/zitadel.AdaptFunc.func1.3(0x2e1bae8, 0xc0000fe380, 0xc0009813e0, 0x2, 0x3, 0xc000346160)
	/go/src/github.com/caos/zitadel/operator/zitadel/kinds/iam/zitadel/adapt.go:335 +0x5c5
github.com/caos/zitadel/operator.QueriersToEnsureFunc(0xc000722780, 0x2b48328, 0x2b48328, 0x2b48320, 0x2b48330, 0x0, 0x2a3ce01, 0xc000346100, 0x4, 0x4, ...)
	/go/src/github.com/caos/zitadel/operator/adapt.go:87 +0x112
github.com/caos/zitadel/operator/zitadel/kinds/orb.AdaptFunc.func1.2(0x2e1bae8, 0xc0000fe380, 0xc0009813b0, 0x2b48320, 0x2b48330, 0x0)
	/go/src/github.com/caos/zitadel/operator/zitadel/kinds/orb/adapt.go:136 +0x290
github.com/caos/zitadel/operator/crtlcrd/zitadel.Takeoff(0xc000722780, 0x2b48328, 0x2b48328, 0x2b48320, 0x2b48330, 0x0, 0x2e1bae8, 0xc0000fe380, 0xc0003ba5f0, 0x1, ...)
	/go/src/github.com/caos/zitadel/operator/crtlcrd/zitadel/zitadel.go:61 +0x126
github.com/caos/zitadel/operator/crtlcrd/zitadel.(*Reconciler).Reconcile(0xc000459680, 0x2de0458, 0xc000722750, 0xc00070a040, 0xb, 0xc00070a024, 0x7, 0xc000722700, 0x0, 0x0, ...)
	/go/src/github.com/caos/zitadel/operator/crtlcrd/zitadel/zitadel.go:39 +0x4bd
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0xc0008edae0, 0x2de0458, 0xc000722720, 0xc00070a040, 0xb, 0xc00070a024, 0x7, 0xc000722700, 0x0, 0x0, ...)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.2/pkg/internal/controller/controller.go:114 +0x247
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0008edae0, 0x2de03b0, 0xc0007ad900, 0x26f41e0, 0xc0002ae1c0)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.2/pkg/internal/controller/controller.go:311 +0x305
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0008edae0, 0x2de03b0, 0xc0007ad900, 0x0)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.2/pkg/internal/controller/controller.go:266 +0x205
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2(0xc000676aa0, 0xc0008edae0, 0x2de03b0, 0xc0007ad900)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.2/pkg/internal/controller/controller.go:227 +0x6b
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.2/pkg/internal/controller/controller.go:223 +0x425
```

**To Reproduce**
```
kind create cluster
curl -L -o zitadelctl https://github.com/caos/zitadel/releases/download/v1.48.5/zitadelctl-linux-amd64
chmod +x zitadelctl
./zitadelctl takeoff
curl -o database.yaml https://docs.zitadel.ch/assets/files/database-51ebbd568effd89805227c7afc1be4a9.yml
curl -o zitadel.yaml https://docs.zitadel.ch/assets/files/zitadel-9d6f8ed2288d244a079057a4339f02a0.yml
kubectl apply -f ./database.yaml,./zitadel.yaml
kubectl delete -f database.yaml -f zitadel.yaml
```

**Expected behavior**
* Operators do not panic
* Created resources are removed

**Comment by eliobischof** [comment]
@dvob this issue popped up again, today. Sorry for the late reply!

We worked hard to make ZITADEL v2 along with CockroachDB easily deployable on kubernetes via [helm](https://github.com/zitadel/zitadel-charts). We are still improving the charts release process, but the chart downloaded via git clone should work fine already, also with KinD.

Would that satisfy your needs too? Otherwise, please reopen the issue.
