### ISSUE TITLE
SEGFAULT on AWS App Runner with v2

### ISSUE THREAD

**Issue by Alexei-Barnes** [zitadel/zitadel#3625]
**Describe the bug**
On AWS App Runner (which is based on AWS ECS), I'm unable to run Zitadel v2 because the container segfaults during configuration.

**Stack Trace**
Note, this log is in reverse chronological order (the ordering of CloudWatch logs in AWS, so read it from top to bottom in terms of time, but the stack trace from top to bottom as that's all sent as a single message.

```
05-09-2022 05:54:00 PM 	/home/runner/work/zitadel/zitadel/main.go:13 +0x76
05-09-2022 05:54:00 PM main.main()
05-09-2022 05:54:00 PM 	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:902
05-09-2022 05:54:00 PM github.com/spf13/cobra.(*Command).Execute(...)
05-09-2022 05:54:00 PM 	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:974 +0x3bc
05-09-2022 05:54:00 PM github.com/spf13/cobra.(*Command).ExecuteC(0xc0000d4000)
05-09-2022 05:54:00 PM 	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:860 +0x5f8
05-09-2022 05:54:00 PM github.com/spf13/cobra.(*Command).execute(0xc000302a00, {0xc000569860, 0x6, 0x6})
05-09-2022 05:54:00 PM 	/home/runner/work/zitadel/zitadel/cmd/admin/start/start_from_init.go:35 +0x299
05-09-2022 05:54:00 PM github.com/zitadel/zitadel/cmd/admin/start.NewStartFromInit.func1(0xc000302a00, {0x1dc319c, 0x6, 0x6})
05-09-2022 05:54:00 PM 	/home/runner/work/zitadel/zitadel/cmd/admin/start/start.go:96 +0x311
05-09-2022 05:54:00 PM github.com/zitadel/zitadel/cmd/admin/start.startZitadel(0xc00038c300, {0x7ffdb0ad1df5, 0x20})
05-09-2022 05:54:00 PM 	/home/runner/work/zitadel/zitadel/internal/query/query.go:69 +0x307
05-09-2022 05:54:00 PM github.com/zitadel/zitadel/internal/query.StartQueries({0x362f8a8, 0xc00012c000}, 0xc000b372e0, 0xc0000fc000, {0x2540be400, 0x3b9aca00, 0x5, 0xc8, 0xc000af9a40, 0x1}, ...)
05-09-2022 05:54:00 PM 	/home/runner/work/zitadel/zitadel/internal/query/projection/projection.go:37 +0x1a8
05-09-2022 05:54:00 PM github.com/zitadel/zitadel/internal/query/projection.Start({0x362f8a8, 0xc00012c000}, 0x0, 0x20, {0x2540be400, 0x3b9aca00, 0x5, 0xc8, 0xc000af9a40, 0x1}, ...)
05-09-2022 05:54:00 PM 	/home/runner/work/zitadel/zitadel/internal/query/projection/org.go:53 +0x808
05-09-2022 05:54:00 PM github.com/zitadel/zitadel/internal/query/projection.NewOrgProjection({0x362f8a8, 0xc00012c000}, {{{0xc000b372e0}, {0x1ddc23e, 0x10}, 0x2540be400, 0x3b9aca00}, 0xc0000fc000, {0x1df7949, 0x1d}, ...})
05-09-2022 05:54:00 PM 	/home/runner/work/zitadel/zitadel/internal/eventstore/handler/crdb/handler_stmt.go:76 +0x334
05-09-2022 05:54:00 PM github.com/zitadel/zitadel/internal/eventstore/handler/crdb.NewStatementHandler({_, _}, {{{0xc000b372e0}, {0x1ddc23e, 0x10}, 0x2540be400, 0x3b9aca00}, 0xc0000fc000, {0x1df7949, 0x1d}, ...})
05-09-2022 05:54:00 PM 	/home/runner/work/zitadel/zitadel/internal/eventstore/handler/crdb/lock.go:36 +0x65
05-09-2022 05:54:00 PM github.com/zitadel/zitadel/internal/eventstore/handler/crdb.NewLocker(0xc0000fc000, {0x1dddfc4, 0x11}, {0x1ddc23e, 0x10})
05-09-2022 05:54:00 PM 	/home/runner/work/zitadel/zitadel/internal/id/sonyflake.go:23 +0x1c
05-09-2022 05:54:00 PM github.com/zitadel/zitadel/internal/id.(*sonyflakeGenerator).Next(0xc000b419c0)
05-09-2022 05:54:00 PM 	/home/runner/go/pkg/mod/github.com/sony/sonyflake@v1.0.0/sonyflake.go:89 +0x3d
05-09-2022 05:54:00 PM github.com/sony/sonyflake.(*Sonyflake).NextID(0x0)
05-09-2022 05:54:00 PM goroutine 1 [running]:
05-09-2022 05:54:00 PM [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x9f4fdd]
05-09-2022 05:54:00 PM panic: runtime error: invalid memory address or nil pointer dereference
05-09-2022 05:54:00 PM time="2022-05-09T16:54:00Z" level=info msg="starting handler" caller="/home/runner/work/zitadel/zitadel/internal/eventstore/handler/handler_projection.go:80" projection=projections.orgs
05-09-2022 05:53:58 PM time="2022-05-09T16:53:58Z" level=info msg="verify zitadel" caller="/home/runner/work/zitadel/zitadel/cmd/admin/initialise/verify_zitadel.go:97" database=zitadel
05-09-2022 05:53:57 PM time="2022-05-09T16:53:57Z" level=info msg="verify grant" caller="/home/runner/work/zitadel/zitadel/cmd/admin/initialise/verify_grant.go:39" database=zitadel user=zitadel
05-09-2022 05:53:57 PM time="2022-05-09T16:53:57Z" level=info msg="verify user" caller="/home/runner/work/zitadel/zitadel/cmd/admin/initialise/verify_user.go:43" username=zitadel
05-09-2022 05:53:57 PM time="2022-05-09T16:53:57Z" level=info msg="initialization started" caller="/home/runner/work/zitadel/zitadel/cmd/admin/initialise/init.go:52"
```

**To Reproduce**
1. Create an ECR repository and upload a configured copy of the zitadel v2 container (I just used docker build with FROM set to the zitadel release `v1.80.0-v2.20-amd64` and copy in my config file).
2. Create an AWS App Runner service, based off of that ECR image.
3. Wait for the task to start up and watch the logs

**Expected behavior**
No segfault.

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
Based on conversations in Discord, it was identified that the cause of this problem is down to trying to uniquely identify the machine: https://discord.com/channels/927474939156643850/927866013545025566/973323013216931891

I'm creating a PR to fix this myself based on that discussion.

**Comment by fforootd** [comment]
For further reference, the related discussion is located here https://discord.com/channels/927474939156643850/973564393134628954
