### ISSUE TITLE
Segmentation Fault when starting ziptadel server 

### ISSUE THREAD

**Issue by mzch** [zitadel/zitadel#4456]
**Describe the bug**
Segmantation fault happens when `start-from-init` or `setup`.

**To Reproduce**
1. do `/usr/local/sbin/zitadel setup --config ./config/zitadel-config.yaml --config ./config/zitadel-secrets.yaml --config ./config/zitadel-init-steps.yaml --masterkeyFile ./config/master.key --tlsMode disabled` 

**Expected behavior**
`start-from-init` or `setup` finished successfully.

**Log**
```
INFO[0000] setup started                                 caller="/home/runner/work/zitadel/zitadel/cmd/setup/setup.go:57"
INFO[0000] verify migration 01_tables                    caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:33"
INFO[0000] starting migration 01_tables                  caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:43"
INFO[0002] verify migration 02_assets                    caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:33"
INFO[0002] starting migration 02_assets                  caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:43"
INFO[0002] verify migration 03_default_instance          caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:33"
INFO[0002] starting migration 03_default_instance        caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:43"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x9bbcfd]

goroutine 1 [running]:
github.com/sony/sonyflake.(*Sonyflake).NextID(0x0)
	/home/runner/go/pkg/mod/github.com/sony/sonyflake@v1.0.0/sonyflake.go:89 +0x3d
github.com/zitadel/zitadel/internal/id.(*sonyflakeGenerator).Next(0x4171eb?)
	/home/runner/work/zitadel/zitadel/internal/id/sonyflake.go:26 +0x1c
github.com/zitadel/zitadel/internal/command.(*Commands).SetUpInstance(0xc0007ea000, {0x39bf548, 0xc0000d8000}, 0xc0005a7ca8)
	/home/runner/work/zitadel/zitadel/internal/command/instance.go:146 +0x5a
github.com/zitadel/zitadel/cmd/setup.(*FirstInstance).Execute(0xc0005a7b80, {0x39bf548, 0xc0000d8000})
	/home/runner/work/zitadel/zitadel/cmd/setup/03.go:91 +0x48c
github.com/zitadel/zitadel/internal/migration.Migrate({0x39bf548, 0xc0000d8000}, 0xc0000c0900?, {0x39b4030?, 0xc0005a7b80?})
	/home/runner/work/zitadel/zitadel/internal/migration/migration.go:44 +0x1a5
github.com/zitadel/zitadel/cmd/setup.Setup(0xc0002ebb00, 0xc000598b00, {0xc000001100, 0x20})
	/home/runner/work/zitadel/zitadel/cmd/setup/setup.go:97 +0xa6b
github.com/zitadel/zitadel/cmd/setup.New.func1(0xc000792c80?, {0x2036a1f?, 0xa?, 0xa?})
	/home/runner/work/zitadel/zitadel/cmd/setup/setup.go:41 +0x38f
github.com/spf13/cobra.(*Command).execute(0xc000792c80, {0xc0002497c0, 0xa, 0xa})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:860 +0x663
github.com/spf13/cobra.(*Command).ExecuteC(0xc000247900)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:974 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:902
main.main()
	/home/runner/work/zitadel/zitadel/main.go:14 +0x74
```
**Server (please complete the following information):**
 - OS: Debian 11.5

**Additional context**

**Comment by fforootd** [comment]
Hi @mzch 

Thanks for raising this.

What ZITADEL version are you experiencing this?

@adlerhurst to me it looks like a problem with the sonyflake, whats you take on this?

**Comment by mzch** [comment]
I got and tried `v2.6.0`.

**Comment by adlerhurst** [comment]
I will have a look at it today. There are multiple of this kind of issues

**Comment by mzch** [comment]
There is still this issue in `v2.7.0`.

**Comment by mzch** [comment]
FYI, my cpu info:
```
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 62
model name	: Intel(R) Xeon(R) CPU E5-2670 v2 @ 2.50GHz
stepping	: 4
microcode	: 0x1
cpu MHz		: 2499.998
cache size	: 16384 KB
physical id	: 0
siblings	: 1
core id		: 0
cpu cores	: 1
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon rep_good nopl xtopology cpuid tsc_known_freq pni pclmulqdq ssse3 cx16 pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm pti ssbd ibrs ibpb stibp fsgsbase tsc_adjust smep erms xsaveopt arat md_clear
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit mmio_unknown
bogomips	: 4999.99
clflush size	: 64
cache_alignment	: 64
address sizes	: 46 bits physical, 48 bits virtual
power management:
```

**Comment by adlerhurst** [comment]
how did you configure the `Machine` in your configuration? There is an uncaught error at the moment. But the problem is a configuration issue

**Comment by mzch** [comment]
Oh, I forgot it.

**zitadel-config.yaml**
```
# All possible options and their defaults: https://github.com/zitadel/zitadel/blob/main/cmd/defaults.yaml

Log:
  Level: 'info'

# Port ZITADEL will listen on
Port: 8801
# Port ZITADEL is exposed on, it can differ from port e.g. if you proxy the traffic
# !!! Changing this after initial setup breaks your system !!!
ExternalPort: 443
# Domain / hostname ZITADEL is exposed externally
# !!! Changing this after initial setup breaks your system !!!
ExternalDomain: example.com
# specifies if ZITADEL is exposed externally through TLS
# this must be set to true even if TLS is not enabled on ZITADEL itself
# but TLS traffic is terminated on a reverse proxy
# !!! Changing this after initial setup breaks your system !!!
ExternalSecure: true

# If not using the docker compose example, adjust these values for connecting ZITADEL to your CockroachDB
Database:
  cockroach:
    Host: 'db.example.com'
    User:
      SSL:
        Mode: 'verify-full'
        RootCert: "/usr/local/share/cockroach/certs/ca.crt"
        Cert: "/usr/local/share/cockroach/certs/client.zitadel.crt"
        Key: "/usr/local/share/cockroach/certs/client.zitadel.key"
    Admin:
      SSL:
        Mode: 'verify-full'
        RootCert: "/usr/local/share/cockroach/certs/ca.crt"
        Cert: "/usr/local/share/cockroach/certs/client.root.crt"
        Key: "/usr/local/share/cockroach/certs/client.root.key"

# this configuration sets the default email configuration
SMTPConfiguration:
  # configuration of the host
  SMTP:
    #for example smtp.mailtrap.io:2525
    Host: mx1.mail-services.net:465
    User: user@example.com
    Password: xxx
  TLS:
  # if the host of the sender is different from ExternalDomain set DefaultInstance.DomainPolicy.SMTPSenderAddressMatchesInstanceDomain to false
  From: no-reply@example.com
  FromName: ZITADEL
```

**zitadel-init-steps.yaml**
```
# All possible options and their defaults: https://github.com/zitadel/zitadel/blob/main/cmd/setup/steps.yaml
FirstInstance:
  Org:
    Human:
      # use the loginname root@zitadel.localhost
      Username: 'username'
      FirstName: Koichi
      LastName: MATSUMOTO
      NickName: koichi
      DisplayName: Koichi MATSUMOTO
      Email:
        Address: mzch@example.com
        Verified: true
      PreferredLanguage: en
      Gender: male
      Password: 'xxx'
```

**zitadel-secrets.yaml**
```
# All possible options and their defaults: https://github.com/zitadel/zitadel/blob/main/cmd/defaults.yaml

# If not using the docker compose example, adjust these values for connecting ZITADEL to your CockroachDB
Database:
  cockroach:
    User:
      # If the user doesn't exist already, it is created
      Username: 'zitadel'
      Password: 'xxx'
    Admin:
      Username: 'root'
      Password: ''
```

**Command line**
```
/usr/local/sbin/zitadel start-from-init --config ./config/zitadel-config.yaml --config ./config/zitadel-secrets.yaml --config ./config/zitadel-init-steps.yaml --masterkeyFile ./config/master.key --tlsMode external
```

**Comment by mzch** [comment]
I changed `zitadel-init-steps.yaml` as below:
```
# All possible options and their defaults: https://github.com/zitadel/zitadel/blob/main/cmd/setup/steps.yaml
FirstInstance:
  InstanceName: ZITADEL
  DefaultLanguage: en
  Org:
    Name: ZITADEL
    Human:
      # use the loginname root@zitadel.localhost
      Username: username
      FirstName: Koichi
      LastName: MATSUMOTO
      NickName:
      DisplayName:
      Email:
        Address:
        Verified: true
      PreferredLanguage: en
      Gender:
      Phone:
        Number:
        Verified:
      Password: Terminus12
      PasswordChangeRequired: true
```
Then, the error message changed:
```
INFO[0000] initialization started                        caller="/home/runner/work/zitadel/zitadel/cmd/initialise/init.go:72"
INFO[0000] verify user                                   caller="/home/runner/work/zitadel/zitadel/cmd/initialise/verify_user.go:38" username=zitadel
INFO[0000] verify database                               caller="/home/runner/work/zitadel/zitadel/cmd/initialise/verify_database.go:38" database=zitadel
INFO[0000] verify grant                                  caller="/home/runner/work/zitadel/zitadel/cmd/initialise/verify_grant.go:33" database=zitadel user=zitadel
INFO[0000] verify zitadel                                caller="/home/runner/work/zitadel/zitadel/cmd/initialise/verify_zitadel.go:69" database=zitadel
INFO[0000] setup started                                 caller="/home/runner/work/zitadel/zitadel/cmd/setup/setup.go:57"
INFO[0000] verify migration 01_tables                    caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:33"
INFO[0000] verify migration 02_assets                    caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:33"
INFO[0000] verify migration 03_default_instance          caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:33"
INFO[0001] verify migration 04_eventstore_indexes        caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:33"
INFO[0001] verify migration config_change                caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:33"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x9bbe9d]

goroutine 1 [running]:
github.com/sony/sonyflake.(*Sonyflake).NextID(0x0)
	/home/runner/go/pkg/mod/github.com/sony/sonyflake@v1.0.0/sonyflake.go:89 +0x3d
github.com/zitadel/zitadel/internal/id.(*sonyflakeGenerator).Next(0x451c49?)
	/home/runner/work/zitadel/zitadel/internal/id/sonyflake.go:26 +0x1c
github.com/zitadel/zitadel/internal/eventstore/handler/crdb.NewLocker(0xc000a5c000, {0x205db85, 0x11}, {0x205bb1a, 0x10})
	/home/runner/work/zitadel/zitadel/internal/eventstore/handler/crdb/lock.go:39 +0x5f
github.com/zitadel/zitadel/internal/eventstore/handler/crdb.NewStatementHandler({_, _}, {{{0xc000258ea0}, {0x205bb1a, 0x10}, 0xdf8475800, 0x3b9aca00, 0x5, 0x1}, 0xc000a5c000, ...})
	/home/runner/work/zitadel/zitadel/internal/eventstore/handler/crdb/handler_stmt.go:75 +0x2ee
github.com/zitadel/zitadel/internal/query/projection.newOrgProjection({0x39ce0e8, 0xc000138000}, {{{0xc000258ea0}, {0x205bb1a, 0x10}, 0xdf8475800, 0x3b9aca00, 0x5, 0x1}, 0xc000a5c000, ...})
	/home/runner/work/zitadel/zitadel/internal/query/projection/org.go:53 +0x9c8
github.com/zitadel/zitadel/internal/query/projection.Start({0x39ce0e8, 0xc000138000}, 0x7f3c601b5108?, 0x30?, {0xdf8475800, 0x3b9aca00, 0x5, 0x1, 0xc8, 0xc000ad6900, ...}, ...)
	/home/runner/work/zitadel/zitadel/internal/query/projection/projection.go:85 +0x24b
github.com/zitadel/zitadel/internal/query.StartQueries({0x39ce0e8, 0xc000138000}, _, _, {0xdf8475800, 0x3b9aca00, 0x5, 0x1, 0xc8, 0xc000ad6900, ...}, ...)
	/home/runner/work/zitadel/zitadel/internal/query/query.go:83 +0x3fd
github.com/zitadel/zitadel/cmd/start.startZitadel(0xc00012fc00, {0xc0005386e0, 0x20})
	/home/runner/work/zitadel/zitadel/cmd/start/start.go:107 +0x3c7
github.com/zitadel/zitadel/cmd/start.NewStartFromInit.func1(0xc00051ca00?, {0x20414ff?, 0xa?, 0xa?})
	/home/runner/work/zitadel/zitadel/cmd/start/start_from_init.go:40 +0x3b7
github.com/spf13/cobra.(*Command).execute(0xc00051ca00, {0xc00013d360, 0xa, 0xa})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:860 +0x663
github.com/spf13/cobra.(*Command).ExecuteC(0xc000236f00)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:974 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:902
main.main()
	/home/runner/work/zitadel/zitadel/main.go:14 +0x74
```

**Comment by mzch** [comment]
Hi, I tried zitadel on my Mac, but at the near point it crashed. Perhaps I have wrong configs but I don't know what's wrong.

```
mzch@mzch-Mac-Studio zitadel % ./zitadel start-from-init --config ./config/zitadel-config.yaml --config ./config/zitadel-secrets.yaml --steps ./config/zitadel-init-steps.yaml --masterkeyFile ./config/master.key --tlsMode disabled
INFO[0000] initialization started                        caller="/home/runner/work/zitadel/zitadel/cmd/initialise/init.go:72"
INFO[0005] verify user                                   caller="/home/runner/work/zitadel/zitadel/cmd/initialise/verify_user.go:38" username=zitadel
INFO[0006] verify database                               caller="/home/runner/work/zitadel/zitadel/cmd/initialise/verify_database.go:38" database=zitadel
INFO[0006] verify grant                                  caller="/home/runner/work/zitadel/zitadel/cmd/initialise/verify_grant.go:33" database=zitadel user=zitadel
INFO[0006] verify zitadel                                caller="/home/runner/work/zitadel/zitadel/cmd/initialise/verify_zitadel.go:69" database=zitadel
INFO[0010] setup started                                 caller="/home/runner/work/zitadel/zitadel/cmd/setup/setup.go:57"
INFO[0011] verify migration 01_tables                    caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:33"
INFO[0011] verify migration 02_assets                    caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:33"
INFO[0012] verify migration 03_default_instance          caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:33"
INFO[0012] verify migration 04_eventstore_indexes        caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:33"
INFO[0012] verify migration config_change                caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:33"
INFO[0013] starting migration config_change              caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:43"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x28 pc=0x10170c948]

goroutine 1 [running]:
github.com/zitadel/zitadel/internal/command.(*SystemConfigWriteModel).NewChangedEvents(0x1400026f400, 0x140000560b8?)
	/home/runner/work/zitadel/zitadel/internal/command/system_model.go:147 +0x318
github.com/zitadel/zitadel/internal/command.(*Commands).prepareChangeSystemConfig.func1({0x104114778?, 0x140000560b8?}, 0x9?)
	/home/runner/work/zitadel/zitadel/internal/command/instance.go:468 +0x8c
github.com/zitadel/zitadel/internal/command.(*Commands).ChangeSystemConfig(0x14000a90420, {0x104114778, 0x140000560b8}, {0x140024ac210?, 0x0?}, 0x0?, 0x0?)
	/home/runner/work/zitadel/zitadel/internal/command/instance.go:438 +0x9c
github.com/zitadel/zitadel/cmd/setup.(*externalConfigChange).Execute(0x140013901c0, {0x104114778, 0x140000560b8})
	/home/runner/work/zitadel/zitadel/cmd/setup/config_change.go:58 +0xd8
github.com/zitadel/zitadel/internal/migration.Migrate({0x104114778, 0x140000560b8}, 0x14000000900?, {0x1060dc850?, 0x140013901c0?})
	/home/runner/work/zitadel/zitadel/internal/migration/migration.go:44 +0x130
github.com/zitadel/zitadel/cmd/setup.Setup(0x14000709680, 0x140020bb180, {0x140006a0840, 0x20})
	/home/runner/work/zitadel/zitadel/cmd/setup/setup.go:103 +0xaec
github.com/zitadel/zitadel/cmd/start.NewStartFromInit.func1(0x14000268280?, {0x1022150c8?, 0xa?, 0xa?})
	/home/runner/work/zitadel/zitadel/cmd/start/start_from_init.go:36 +0x2d4
github.com/spf13/cobra.(*Command).execute(0x14000268280, {0x1400026ef00, 0xa, 0xa})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:860 +0x4ac
github.com/spf13/cobra.(*Command).ExecuteC(0x14000222f00)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:974 +0x354
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:902
main.main()
	/home/runner/work/zitadel/zitadel/main.go:14 +0x7c
```

**zitadel-config.yaml**
```
# All possible options and their defaults: https://github.com/zitadel/zitadel/blob/main/cmd/defaults.yaml
Log:
  Level: 'info'

# Make ZITADEL accessible over HTTP, not HTTPS
ExternalSecure: false

# If not using the docker compose example, adjust these values for connecting ZITADEL to your CockroachDB
Database:
  cockroach:
    Host: 'db.leafia.net'
    User:
      SSL:
        Mode: 'verify-full'
        RootCert: "./certs/ca.crt"
        Cert: "./certs/client.zitadel.crt"
        Key: "./certs/client.zitadel.key"
    Admin:
      SSL:
        Mode: 'verify-full'
        RootCert: "./certs/ca.crt"
        Cert: "./certs/client.root.crt"
        Key: "./certs/client.root.key"
```
**zitadel-init-steps.yaml**
```
FirstInstance:
  Org:
    Human:
      # use the loginname root@zitadel.localhost
      Username: 'root'
      Password: 'RootPassword1!'
```
**zitadel-secrets.yaml**
```
# All possible options and their defaults: https://github.com/zitadel/zitadel/blob/main/cmd/defaults.yaml

# If not using the docker compose example, adjust these values for connecting ZITADEL to your CockroachDB
Database:
  cockroach:
    User:
      # If the user doesn't exist already, it is created
      Username: 'zitadel'
      Password: 'xxx'
    Admin:
      Username: 'root'
      Password: ''
```

- Mac Studio (M1 Ultra)
- OS: macOS `12.6`
- CockroachDB: `v22.1.7`

**Comment by adlerhurst** [comment]
Okay it looks like your container has no ip or is not connected to the internet. I will give you more exact feedback asap

**Comment by mzch** [comment]
> how did you configure the `Machine` in your configuration? There is an uncaught error at the moment. But the problem is a configuration issue

Oh sorry, I missed your advice. when adding `Machine` section, zitadel reported a different error:
```
INFO[0000] initialization started                        caller="/home/runner/work/zitadel/zitadel/cmd/initialise/init.go:72"
INFO[0000] verify user                                   caller="/home/runner/work/zitadel/zitadel/cmd/initialise/verify_user.go:38" username=zitadel
INFO[0000] verify database                               caller="/home/runner/work/zitadel/zitadel/cmd/initialise/verify_database.go:38" database=zitadel
INFO[0000] verify grant                                  caller="/home/runner/work/zitadel/zitadel/cmd/initialise/verify_grant.go:33" database=zitadel user=zitadel
INFO[0001] verify zitadel                                caller="/home/runner/work/zitadel/zitadel/cmd/initialise/verify_zitadel.go:69" database=zitadel
INFO[0002] setup started                                 caller="/home/runner/work/zitadel/zitadel/cmd/setup/setup.go:57"
INFO[0002] verify migration 01_tables                    caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:33"
INFO[0002] verify migration 02_assets                    caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:33"
INFO[0002] verify migration 03_default_instance          caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:33"
INFO[0002] starting migration 03_default_instance        caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:43"
ERRO[0002] migration failed                              caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:45" error="ID=COMMA-ZDLwA Message=Errors.User.PasswordComplexityPolicy.HasSymbol"
FATA[0002] unable to migrate step 3                      caller="/home/runner/work/zitadel/zitadel/cmd/setup/setup.go:98" error="ID=COMMA-ZDLwA Message=Errors.User.PasswordComplexityPolicy.HasSymbol"
```

**Comment by mzch** [comment]
When removing `--steps` argument and adding `DefaultInstance` section to `zitadel-config.yaml`, I booted up zitadel successfully. But I can't login. Zitadel said `User could not be found`. I've given up. Thanks.

**Comment by fforootd** [comment]
Sorry to hear that you have given up.

I think you needed to input the user in the way of username@orgname.domainname

In your case I think the would be root@zitadel.auth6.com (Zitadel is the default orgname)

**Comment by mzch** [comment]
Thanks for your effot. However, unforunatelly I'd have to say it's much more dificult to setup Zitadel than KeyCloak.

**Comment by fforootd** [comment]
> Thanks for your effot. However, unforunatelly I'd have to say it's much more dificult to setup Zitadel than KeyCloak.

Thanks for this input. This is the first time someone told us this 😞 

There is certainly room for improvement. Care to share what you preferred when using Keycloak?

**Comment by mzch** [comment]
I think Zitadel is more modern and custaimizable than KeyCloak. Its' a great benefit to me. But for some reasone I can't run it easily while I put config files as prescribeed in the [document](https://docs.zitadel.com/docs/guides/manage/self-hosted/configure). It's a pity.
