### ISSUE TITLE
Setting up SMTP 

### ISSUE THREAD

**Issue by hifabienne** [zitadel/zitadel#4994]
As a ZITADEL Admin, I want to be able to setup my own SMTP provider, with the authentication my provider needs.

**Acceptance criteria**
- [ ] I want to be able to setup SMTP without a user and password

**Comment by dasrocky** [comment]
Just came across this during deployment, that Zitadel generic doesn't work without a username & password. 

another similar issue:
https://github.com/orgs/zitadel/projects/2/views/1?filterQuery=title%3A*smtp*&pane=issue&itemId=71589694&issue=zitadel%7Czitadel%7C8344

Are there any updates on this implementation? Or workarounds? Please.

Self-hosted ZITADEL Version:
v2.56.0

**Comment by t40mas** [comment]
You can create a generic smtp without username and a blank as password by just removing the disabled flag via inspector in your browser.

<img width="379" alt="Image" src="https://github.com/user-attachments/assets/b433b9c7-37b3-406f-9f82-e514efa2d9dd" />

**Comment by jean-loutre** [comment]
> You can create a generic smtp without username and a blank as password by just removing the disabled flag via inspector in your browser.

that doesn't work with the latest Zitadel version (clicking the button enabled via the inspector does nothing).

**Comment by alaincao** [comment]
the creation of the configuration is not a problem with your "hack",
but clicking the "Test" button crashes the application...

```
zitadel-1    | panic: runtime error: invalid memory address or nil pointer dereference
zitadel-1    | [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xd8d56f]
zitadel-1    | 
zitadel-1    | goroutine 1417 [running]:
zitadel-1    | github.com/zitadel/zitadel/internal/crypto.checkEncryptionAlgorithm(0x0, {0x6c6fdd0, 0xc003487140})
zitadel-1    |  /home/runner/work/zitadel/zitadel/internal/crypto/crypto.go:107 +0x2f
zitadel-1    | github.com/zitadel/zitadel/internal/crypto.DecryptString(0x0, {0x6c6fdd0, 0xc003487140})
zitadel-1    |  /home/runner/work/zitadel/zitadel/internal/crypto/crypto.go:100 +0x25
zitadel-1    | github.com/zitadel/zitadel/internal/command.(*Commands).TestSMTPConfig(0xc001d66c88, {0x6c61dd8?, 0xc0057111a0?}, {0xc002a46fc0?, 0xc0057111a0?}, {0xc00165d9c8?, 0x475b39?}, {0xc00165d9b0, 0x14}, 0xc0056da3d8)
zitadel-1    |  /home/runner/work/zitadel/zitadel/internal/command/smtp.go:433 +0x165
zitadel-1    | github.com/zitadel/zitadel/internal/api/grpc/admin.(*Server).TestSMTPConfig(0xc001069ac0, {0x6c61dd8, 0xc0057111a0}, 0xc00561e280)
zitadel-1    |  /home/runner/work/zitadel/zitadel/internal/api/grpc/admin/smtp.go:128 +0x179
zitadel-1    | github.com/zitadel/zitadel/pkg/grpc/admin._AdminService_TestSMTPConfig_Handler.func1({0x6c61dd8?, 0xc0057111a0?}, {0x4054560?, 0xc00561e280?})
zitadel-1    |  /home/runner/work/zitadel/zitadel/pkg/grpc/admin/admin_grpc.pb.go:3934 +0xce
zitadel-1    | github.com/zitadel/zitadel/internal/api/grpc/server.CreateServer.ActivityInterceptor.func13({0x6c61dd8, 0xc005711140}, {0x4054560, 0xc00561e280}, 0xc0052795c0, 0xc00372af78)
zitadel-1    |  /home/runner/work/zitadel/zitadel/internal/api/grpc/server/middleware/activity_interceptor.go:19 +0x8c
zitadel-1    | github.com/zitadel/zitadel/internal/api/grpc/server.CreateServer.ChainUnaryServer.func15.1({0x6c61dd8?, 0xc005711140?}, {0x4054560?, 0xc00561e280?})
zitadel-1    |  /home/runner/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/chain.go:48 +0x45
zitadel-1    | github.com/zitadel/zitadel/internal/api/grpc/server.CreateServer.ServiceHandler.func12({0x6c61dd8, 0xc0056ec870}, {0x4054560, 0xc00561e280}, 0xc00561e280?, 0xc005854740)
zitadel-1    |  /home/runner/work/zitadel/zitadel/internal/api/grpc/server/middleware/service_interceptor.go:19 +0x82
zitadel-1    | github.com/zitadel/zitadel/internal/api/grpc/server.CreateServer.ChainUnaryServer.func15.1({0x6c61dd8?, 0xc0056ec870?}, {0x4054560?, 0xc00561e280?})
zitadel-1    |  /home/runner/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/chain.go:48 +0x45
zitadel-1    | github.com/zitadel/zitadel/internal/api/grpc/server/middleware.validate({0x6c61dd8, 0xc0056ec870}, {0x4054560, 0xc00561e280}, 0xe00045?, 0xc005854780)
zitadel-1    |  /home/runner/work/zitadel/zitadel/internal/api/grpc/server/middleware/validation_interceptor.go:35 +0x168
zitadel-1    | github.com/zitadel/zitadel/internal/api/grpc/server.CreateServer.ValidationHandler.func11({0x6c61dd8?, 0xc0056ec870?}, {0x4054560?, 0xc00561e280?}, 0xc0056da528?, 0xc0056da640?)
zitadel-1    |  /home/runner/work/zitadel/zitadel/internal/api/grpc/server/middleware/validation_interceptor.go:16 +0x27
zitadel-1    | github.com/zitadel/zitadel/internal/api/grpc/server.CreateServer.ChainUnaryServer.func15.1({0x6c61dd8?, 0xc0056ec870?}, {0x4054560?, 0xc00561e280?})
zitadel-1    |  /home/runner/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/chain.go:48 +0x45
zitadel-1    | github.com/zitadel/zitadel/internal/api/grpc/server.CreateServer.ExecutionHandler.func10({0x6c61dd8, 0xc0056ec870}, {0x4054560, 0xc00561e280}, 0xc0052795c0, 0xc0058547c0)
zitadel-1    |  /home/runner/work/zitadel/zitadel/internal/api/grpc/server/middleware/execution_interceptor.go:27 +0xe8
zitadel-1    | github.com/zitadel/zitadel/internal/api/grpc/server.CreateServer.ChainUnaryServer.func15.1({0x6c61dd8?, 0xc0056ec870?}, {0x4054560?, 0xc00561e280?})
zitadel-1    |  /home/runner/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/chain.go:48 +0x45
zitadel-1    | github.com/zitadel/zitadel/internal/api/grpc/server.CreateServer.QuotaExhaustedInterceptor.func9({0x6c61dd8, 0xc0056ec870}, {0x4054560, 0xc00561e280}, 0xc0052795c0, 0xc005854800)
zitadel-1    |  /home/runner/work/zitadel/zitadel/internal/api/grpc/server/middleware/quota_interceptor.go:24 +0x275
zitadel-1    | github.com/zitadel/zitadel/internal/api/grpc/server.CreateServer.ChainUnaryServer.func15.1({0x6c61dd8?, 0xc0056ec870?}, {0x4054560?, 0xc00561e280?})
zitadel-1    |  /home/runner/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/chain.go:48 +0x45
zitadel-1    | github.com/zitadel/zitadel/internal/api/grpc/server.CreateServer.TranslationHandler.func8({0x6c61dd8, 0xc0056ec870}, {0x4054560?, 0xc00561e280?}, 0xc0056ec840?, 0xc0056fc000?)
zitadel-1    |  /home/runner/work/zitadel/zitadel/internal/api/grpc/server/middleware/translation_interceptor.go:17 +0x5d
zitadel-1    | github.com/zitadel/zitadel/internal/api/grpc/server.CreateServer.ChainUnaryServer.func15.1({0x6c61dd8?, 0xc0056ec870?}, {0x4054560?, 0xc00561e280?})
zitadel-1    |  /home/runner/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/chain.go:48 +0x45
zitadel-1    | github.com/zitadel/zitadel/internal/api/grpc/server/middleware.authorize({0x6c61dd8, 0xc0056ce210}, {0x4054560, 0xc00561e280}, 0xc0052795c0, 0xc005854880, {0x6c73ee0, 0xc000278690}, {{0xc002be3080, 0x9, ...}}, ...)
zitadel-1    |  /home/runner/work/zitadel/zitadel/internal/api/grpc/server/middleware/auth_interceptor.go:42 +0x443
zitadel-1    | github.com/zitadel/zitadel/internal/api/grpc/server.CreateServer.AuthorizationInterceptor.func7({0x6c61dd8, 0xc0056ce210?}, {0x4054560?, 0xc00561e280?}, 0x6be1238?, 0xc0058267e0?)
zitadel-1    |  /home/runner/work/zitadel/zitadel/internal/api/grpc/server/middleware/auth_interceptor.go:18 +0x7e
zitadel-1    | github.com/zitadel/zitadel/internal/api/grpc/server.CreateServer.ChainUnaryServer.func15.1({0x6c61dd8?, 0xc0056ce210?}, {0x4054560?, 0xc00561e280?})
zitadel-1    |  /home/runner/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/chain.go:48 +0x45
zitadel-1    | github.com/zitadel/zitadel/internal/api/grpc/server.CreateServer.LimitsInterceptor.func6({0x6c61dd8, 0xc0056ce210}, {0x4054560, 0xc00561e280}, 0xc0052795c0, 0xc0058548c0)
zitadel-1    |  /home/runner/work/zitadel/zitadel/internal/api/grpc/server/middleware/limits_interceptor.go:29 +0x11c
zitadel-1    | github.com/zitadel/zitadel/internal/api/grpc/server.CreateServer.ChainUnaryServer.func15.1({0x6c61dd8?, 0xc0056ce210?}, {0x4054560?, 0xc00561e280?})
zitadel-1    |  /home/runner/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/chain.go:48 +0x45
zitadel-1    | github.com/zitadel/zitadel/internal/api/grpc/server/middleware.toGRPCError({0x6c61dd8?, 0xc0056ce210?}, {0x4054560?, 0xc00561e280?}, 0x0?)
zitadel-1    |  /home/runner/work/zitadel/zitadel/internal/api/grpc/server/middleware/error_interceptor.go:19 +0x2b
zitadel-1    | github.com/zitadel/zitadel/internal/api/grpc/server.CreateServer.ErrorHandler.func5({0x6c61dd8?, 0xc0056ce210?}, {0x4054560?, 0xc00561e280?}, 0x12?, 0x374a401?)
zitadel-1    |  /home/runner/work/zitadel/zitadel/internal/api/grpc/server/middleware/error_interceptor.go:14 +0x2a
zitadel-1    | github.com/zitadel/zitadel/internal/api/grpc/server.CreateServer.ChainUnaryServer.func15.1({0x6c61dd8?, 0xc0056ce210?}, {0x4054560?, 0xc00561e280?})
zitadel-1    |  /home/runner/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/chain.go:48 +0x45
zitadel-1    | github.com/zitadel/zitadel/internal/api/grpc/server.CreateServer.AccessStorageInterceptor.func4({0x6c61dd8, 0xc0056ce210}, {0x4054560, 0xc00561e280}, 0xc0052795c0, 0xc005854940)
zitadel-1    |  /home/runner/work/zitadel/zitadel/internal/api/grpc/server/middleware/access_interceptor.go:21 +0x459
zitadel-1    | github.com/zitadel/zitadel/internal/api/grpc/server.CreateServer.ChainUnaryServer.func15.1({0x6c61dd8?, 0xc0056ce210?}, {0x4054560?, 0xc00561e280?})
zitadel-1    |  /home/runner/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/chain.go:48 +0x45
zitadel-1    | github.com/zitadel/zitadel/internal/api/grpc/server/middleware.addInstanceByRequestedHost({0x6c61dd8, 0xc0057ad380}, {0x4054560, 0xc00561e280}, 0xc005854980, {0x6c4ff70, 0xc002f06000}, 0xc00012d6d0, {0xc0000ba167, 0xd})
zitadel-1    |  /home/runner/work/zitadel/zitadel/internal/api/grpc/server/middleware/instance_interceptor.go:110 +0x3da
zitadel-1    | github.com/zitadel/zitadel/internal/api/grpc/server/middleware.setInstance({0x6c61dd8, 0xc0057ad380}, {0x4054560, 0xc00561e280}, 0xc0052795c0, 0xc005854980, {0x6c4ff70, 0xc002f06000}, {0xc0000ba167, 0xd}, ...)
zitadel-1    |  /home/runner/work/zitadel/zitadel/internal/api/grpc/server/middleware/instance_interceptor.go:65 +0x2c5
zitadel-1    | github.com/zitadel/zitadel/internal/api/grpc/server/middleware.InstanceInterceptor.func1({0x6c61dd8, 0xc0057ad380?}, {0x4054560?, 0xc00561e280?}, 0x1?, 0x1?)
zitadel-1    |  /home/runner/work/zitadel/zitadel/internal/api/grpc/server/middleware/instance_interceptor.go:31 +0x76
zitadel-1    | github.com/zitadel/zitadel/internal/api/grpc/server.CreateServer.ChainUnaryServer.func15.1({0x6c61dd8?, 0xc0057ad380?}, {0x4054560?, 0xc00561e280?})
zitadel-1    |  /home/runner/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/chain.go:48 +0x45
zitadel-1    | github.com/zitadel/zitadel/internal/api/grpc/server.CreateServer.NoCacheInterceptor.func3({0x6c61dd8, 0xc0057ad380}, {0x4054560, 0xc00561e280}, 0xc0052795c0, 0xc0058549c0)
zitadel-1    |  /home/runner/work/zitadel/zitadel/internal/api/grpc/server/middleware/cache_interceptor.go:29 +0x365
zitadel-1    | github.com/zitadel/zitadel/internal/api/grpc/server.CreateServer.ChainUnaryServer.func15.1({0x6c61dd8?, 0xc0057ad380?}, {0x4054560?, 0xc00561e280?})
zitadel-1    |  /home/runner/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/chain.go:48 +0x45
zitadel-1    | github.com/zitadel/zitadel/internal/api/grpc/server/middleware.RegisterMetrics({0x6c61dd8, 0xc0057ad380}, {0x4054560, 0xc00561e280}, 0xc0052795c0, 0xc005854a00, {0xc003580d90, 0x3, 0xc00372af90?}, {0xc0004ab0e0, ...})
zitadel-1    |  /home/runner/work/zitadel/zitadel/internal/api/grpc/server/middleware/metrics_interceptor.go:44 +0x173
zitadel-1    | github.com/zitadel/zitadel/internal/api/grpc/server.CreateServer.MetricsHandler.func2({0x6c61dd8?, 0xc0057ad380?}, {0x4054560?, 0xc00561e280?}, 0xc005649170?, 0x0?)
zitadel-1    |  /home/runner/work/zitadel/zitadel/internal/api/grpc/server/middleware/metrics_interceptor.go:29 +0x53
zitadel-1    | github.com/zitadel/zitadel/internal/api/grpc/server.CreateServer.ChainUnaryServer.func15.1({0x6c61dd8?, 0xc0057ad380?}, {0x4054560?, 0xc00561e280?})
zitadel-1    |  /home/runner/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/chain.go:48 +0x45
zitadel-1    | github.com/zitadel/zitadel/internal/api/grpc/server.CreateServer.CallDurationHandler.func1({0x6c61dd8?, 0xc005649170?}, {0x4054560, 0xc00561e280}, 0xc002ac4860?, 0xc005854a40)
zitadel-1    |  /home/runner/work/zitadel/zitadel/internal/api/grpc/server/middleware/call_interceptor.go:14 +0x43
zitadel-1    | github.com/zitadel/zitadel/internal/api/grpc/server.CreateServer.ChainUnaryServer.func15({0x6c61dd8, 0xc005649170}, {0x4054560, 0xc00561e280}, 0xc0052795c0, 0x80?)
zitadel-1    |  /home/runner/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/chain.go:53 +0x123
zitadel-1    | github.com/zitadel/zitadel/pkg/grpc/admin._AdminService_TestSMTPConfig_Handler({0x4136f20, 0xc001069ac0}, {0x6c61dd8, 0xc005649170}, 0xc005614780, 0xc002ab5800)
zitadel-1    |  /home/runner/work/zitadel/zitadel/pkg/grpc/admin/admin_grpc.pb.go:3936 +0x143
zitadel-1    | google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001f4a00, {0x6c61dd8, 0xc005649050}, 0xc005a70c00, 0xc0037e2090, 0x997b9f0, 0x0)
zitadel-1    |  /home/runner/go/pkg/mod/google.golang.org/grpc@v1.72.1/server.go:1405 +0x1036
zitadel-1    | google.golang.org/grpc.(*Server).handleStream(0xc0001f4a00, {0x6c65b90, 0xc00290c380}, 0xc005a70c00)
zitadel-1    |  /home/runner/go/pkg/mod/google.golang.org/grpc@v1.72.1/server.go:1815 +0xb88
zitadel-1    | google.golang.org/grpc.(*Server).serveStreams.func2.1()
zitadel-1    |  /home/runner/go/pkg/mod/google.golang.org/grpc@v1.72.1/server.go:1035 +0x7f
zitadel-1    | created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 1444
zitadel-1    |  /home/runner/go/pkg/mod/google.golang.org/grpc@v1.72.1/server.go:1046 +0x11d
zitadel-1 exited with code 0
```

**Comment by rltas** [comment]
I'm running Zitadel in a container with a local postfix relay on the host that's handling encryption and authentication with our primary relay. For any other platform I can just provide a relay, Zitadel is the first case where I seem to be forced to specify a username and password.
