### ISSUE TITLE
[Bug]: Zitadel not returning "returnUrl" in state property of token makes zitadel implementation with Blazor Webassembly difficult

### ISSUE THREAD

**Issue by KillTrot** [zitadel/zitadel#5783]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

ZITADEL Cloud

### Describe the bug

If added Authentication to Blazor Webassembly like the docs from Microsoft describe it, the RemoteAuthenticationState expects the State Property of the token response to contain the "returnUrl" (where to go after the authentication).
Auth0, KeyCloak, Authentik, Identity Server and other providers successfully have this property, whereas with Zitadel it's not there, thus resulting in the following exception:

> crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: An exception occurred executing JS interop: The JSON value could not be converted to Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationState. Path: $.state | LineNumber: 0 | BytePositionInLine: 62.. See InnerException for more details.
Microsoft.JSInterop.JSException: An exception occurred executing JS interop: The JSON value could not be converted to Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationState. Path: $.state | LineNumber: 0 | BytePositionInLine: 62.. See InnerException for more details.
 ---> System.Text.Json.JsonException: The JSON value could not be converted to Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationState. Path: $.state | LineNumber: 0 | BytePositionInLine: 62.
   at System.Text.Json.ThrowHelper.ThrowJsonException_DeserializeUnableToConvertValue(Type propertyType)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1[[Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationState, Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=7.0.5.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, RemoteAuthenticationState& value)
   at System.Text.Json.Serialization.JsonConverter`1[[Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationState, Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=7.0.5.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, RemoteAuthenticationState& value)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1[[Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationState, Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=7.0.5.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1[[Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationResult`1[[Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationState, Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=7.0.5.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]], Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=7.0.5.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, RemoteAuthenticationResult`1& value)
   at System.Text.Json.Serialization.JsonConverter`1[[Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationResult`1[[Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationState, Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=7.0.5.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]], Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=7.0.5.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, RemoteAuthenticationResult`1& value)
   at System.Text.Json.Serialization.JsonConverter`1[[Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationResult`1[[Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationState, Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=7.0.5.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]], Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=7.0.5.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.Serialization.JsonConverter`1[[Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationResult`1[[Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationState, Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=7.0.5.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]], Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=7.0.5.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].ReadCoreAsObject(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[Object](Utf8JsonReader& reader, JsonTypeInfo jsonTypeInfo, ReadStack& state)
   at System.Text.Json.JsonSerializer.Read[Object](Utf8JsonReader& reader, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Deserialize(Utf8JsonReader& reader, Type returnType, JsonSerializerOptions options)
   at Microsoft.JSInterop.JSRuntime.EndInvokeJS(Int64 taskId, Boolean succeeded, Utf8JsonReader& jsonReader)
   --- End of inner exception stack trace ---
   at Microsoft.JSInterop.JSRuntime.<InvokeAsync>d__16`1[[Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationResult`1[[Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationState, Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=7.0.5.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]], Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=7.0.5.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].MoveNext()
   at Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService`3.<CompleteSignInAsync>d__21[[Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationState, Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=7.0.5.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteUserAccount, Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=7.0.5.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[Microsoft.AspNetCore.Components.WebAssembly.Authentication.OidcProviderOptions, Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=7.0.5.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].MoveNext()
   at Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticatorViewCore`1.<ProcessLogInCallback>d__86[[Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationState, Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=7.0.5.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].MoveNext()
   at Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticatorViewCore`1.<OnParametersSetAsync>d__84[[Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationState, Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=7.0.5.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].MoveNext()
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)

For comparision, here is how Zitadel returns the token:

> {"id_token":"...","access_token":"...","token_type":"Bearer","scope":"openid profile","profile":{"sub":"212117454011302145","auth_time":1682928334,"amr":["password","pwd"],"azp":"212117668491231489@zitadel-blazorwasm","client_id":"212117668491231489@zitadel-blazorwasm","name":"ZITADEL Admin","given_name":"ZITADEL","family_name":"Admin","locale":"en","updated_at":1682927858,"preferred_username":"KillTrot@killtrot.zitadel.cloud"},"expires_at":1683054204,"state":"cc1d66392fc048519ecf571767922ec3"}

With Auth0:

> {"id_token":"...","access_token":"...","token_type":"Bearer","scope":"openid profile","profile":{"nickname":"admin","name":"admin","picture":"https://s.gravatar.com/avatar/ef5543ac9b7e2afb1b57408c7fb3be97?s=480&r=pg&d=https%3A%2F%2Fcdn.auth0.com%2Favatars%2Fad.png","updated_at":"2023-05-02T07:07:46.249Z","sub":"auth0|644bb8012d2f3d72a6e4a9d5","sid":"8FmszA_XxSqf7jPxwnMLJFYeGrCR46R5"},"expires_at":1683097672,"state":{"returnUrl":"https://localhost:5443/"}}

While it may still be possible to override the default implementation of RemoteAuthenticationState with Blazor WebAssembly, doing so unnecessarily complicates getting started with Zitadel and Blazor WebAssembly.

### To reproduce

- Clone the repository at https://github.com/KillTrot/Zitadel-BlazorWasm
- Open in Visual Studio or Visual Studio Code and run the Blazor WebAssembly application
- Try to authenticate with Zitadel (if necessary, change the client id and url in wwwroot/appsettings.Development.json
- There will be the described exception (for more log messages, enable verbose logging in the developer tools of your browser
- To try with Auth0, change `builder.Configuration.Bind("Zitadel", options.ProviderOptions);` to `builder.Configuration.Bind("Auth0", options.ProviderOptions);` in Client/Program.cs

### Expected behavior

It would make it a lot easier to get started with Blazor WebAssembly and Zitadel if Zitadel would return the "returnUrl" in the token response' state.

**Comment by buehler** [comment]
Addition: I'd check what the spec defines. If state is an arbitrary field, it may be a good idea to implement this behavior in `zitadel-net` instead of doing something in zitadel itself.

And while testing this, I found out that ZITADEL has some restrictive CSP (which makes sense, unless you use ZITADEL in an SPA):

```
Refused to frame 'https://cas-fee-advanced-ocvdad.zitadel.cloud/' because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'none'".
```

It could not create the IFrame to check the authentication state which defeats the purpose of SPA authentication.

**Comment by KillTrot** [comment]
I'm not sure if I've looked in the right place, but [here ](https://openid.net/specs/openid-connect-core-1_0.html#:~:text=REQUIRED.%20ID%20Token.-,state,-OAuth%202.0%20state) it's defined:

> 3.2.2.5.  Successful Authentication Response
When using the Implicit Flow, Authentication Responses are made in the same manner as for the Authorization Code Flow, as defined in [Section 3.1.2.5](https://openid.net/specs/openid-connect-core-1_0.html#AuthResponse), with the exception of the differences specified in this section.
When using the Implicit Flow, all response parameters are added to the fragment component of the Redirection URI, as specified in [OAuth 2.0 Multiple Response Type Encoding Practices](https://openid.net/specs/openid-connect-core-1_0.html#OAuth.Responses) [OAuth.Responses], unless a different Response Mode was specified.
These parameters are returned from the Authorization Endpoint:
access_token
OAuth 2.0 Access Token. This is returned unless the response_type value used is id_token.
token_type
OAuth 2.0 Token Type value. The value MUST be Bearer or another token_type value that the Client has negotiated with the Authorization Server. Clients implementing this profile MUST support the [OAuth 2.0 Bearer Token Usage](https://openid.net/specs/openid-connect-core-1_0.html#RFC6750) [RFC6750] specification. This profile only describes the use of bearer tokens. This is returned in the same cases as access_token is.
id_token
REQUIRED. ID Token.
**state
OAuth 2.0 state value. REQUIRED if the state parameter is present in the Authorization Request. Clients MUST verify that the state value is equal to the value of state parameter in the Authorization Request.**


Also, in 3.1.2.6 of the same document:

> state
OAuth 2.0 state value. REQUIRED if the Authorization Request included the state parameter. Set to the value received from the Client.

**Comment by hifabienne** [comment]
> Addition: I'd check what the spec defines. If state is an arbitrary field, it may be a good idea to implement this behavior in `zitadel-net` instead of doing something in zitadel itself.
> 
> And while testing this, I found out that ZITADEL has some restrictive CSP (which makes sense, unless you use ZITADEL in an SPA):
> 
> ```
> Refused to frame 'https://myinstance-ocvdad.zitadel.cloud/' because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'none'".
> ```
> 
> It could not create the IFrame to check the authentication state which defeats the purpose of SPA authentication.


If you need to run it in an iframe there is a option you can enable a setting in the security policy of your instance:
https://zitadel.com/docs/guides/solution-scenarios/configurations#embedding-zitadel-in-an-iframe

**Comment by KillTrot** [comment]
While changing this setting resolves the error message @buehler mentioned, it is not related to the exception I'm experiencing

**Comment by hifabienne** [comment]
@muhlemmer or @livio-a Can you help here?

**Comment by muhlemmer** [comment]
As far as I can see we do set the state in oidc, if it was indeed part of the request:

https://github.com/zitadel/oidc/blob/7997994be483ad30c994de6a4bcc04f4dce682b7/pkg/op/token.go#L45-L62

The state is returned according to what was set in the Auth Request. As you can see in the response you posted, there is a state field:

```
{"id_token":"...","access_token":"...","token_type":"Bearer","scope":"openid profile","profile":{"sub":"212117454011302145","auth_time":1682928334,"amr":["password","pwd"],"azp":"212117668491231489@zitadel-blazorwasm","client_id":"212117668491231489@zitadel-blazorwasm","name":"ZITADEL Admin","given_name":"ZITADEL","family_name":"Admin","locale":"en","updated_at":1682927858,"preferred_username":"[KillTrot@killtrot.zitadel.cloud](mailto:KillTrot@killtrot.zitadel.cloud)"},"expires_at":1683054204,"state":"cc1d66392fc048519ecf571767922ec3"
```

> `"state":"cc1d66392fc048519ecf571767922ec3"`

A string value, compliant to the standard. Auth0 seems to set a JSON object there, but I can't find in the standard if that is even allowed. Also, I wouldn't work very well because the state is also used in implicit flow redirects (https://openid.net/specs/openid-connect-core-1_0.html#ImplicitAuthResponse) with key-value pairs:

```
  HTTP/1.1 302 Found
  Location: https://client.example.org/cb#
    access_token=SlAV32hkKG
    &token_type=bearer
    &id_token=eyJ0 ... NiJ9.eyJ1c ... I6IjIifX0.DeWt4Qu ... ZXso
    &expires_in=3600
    &state=af0ifjsldkj
```

The client is responsible for creating the state parameter and as far as I can see in the back-end the state is returned as set.

@buehler wrote
> Addition: I'd check what the spec defines. If state is an arbitrary field, it may be a good idea to implement this behavior in `zitadel-net` instead of doing something in zitadel itself.

We would need to change some things in zitadel on oidc as well. Currently the state field is a string type:

https://github.com/zitadel/oidc/blob/7997994be483ad30c994de6a4bcc04f4dce682b7/pkg/oidc/token.go#L213

So if the client would set a JSON there, it will receive a quoted JSON back: `{"State":"{\"returnUrl\":\"https://localhost:5443/\"}"}`, which wouldn't work well either.

We would need to refactor zitadel/oidc to allow for this dual typing, which would constitute a breaking change.

IMO this can be downgraded to a feature request. And if we decide to support this we need to create user-stories in oidc for the breaking change.

**Comment by KillTrot** [comment]
I understand your point and I'm certain that you understand the OICD Specs better than I do, but how does it come that it works with other OICD Providers? I have tested it successfully with Auth0, Authentik and KeyCloak.
None of those needed any special configuration or similar.

**Comment by muhlemmer** [comment]
> but how does it come that it works with other OICD Providers? 

It was not a user case that was taken into consideration because the behavior is specific to a certain vendor, in this case microsoft. As with any software project, features are added based on the need of users over time and probably the others already had users with this need and we didn't.

> None of those needed any special configuration or similar.

In this case we can take it as a feature request and put it in a priority list that is sorted on the needs of clients and users. Or, if you need it more urgently feel free to send a PR since we are also open-source.

**Comment by KillTrot** [comment]
I am sadly not well enough in go to help out here.
Anyway, thanks very much for your efforts and this great project :)

**Comment by elinashoko** [comment]
Thanks for filing this issue. As part of an ongoing backlog cleanup, we're closing issues that have had no activity in over 12 months.

If this is still relevant, let us know in a comment (or reopen the issue) and we'll take another look.

This issue will close in 30 days if there's no further activity.
