### ISSUE TITLE
[Bug]: Can't configure an SMTP provider with no authentication

### ISSUE THREAD

**Issue by Etienne-gh** [zitadel/zitadel#8344]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [ ] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

Tested on 2.55.1, 2.56.0 and development

### Database

CockroachDB

### Describe the problem caused by this bug

Generic SMTP without authentication is not working anymore since I updated Zitadel to 2.55.1 version.

It seems that this feature is still available and  handled by smtpAuth function when username and password are empty: https://github.com/zitadel/zitadel/blob/d90db6693c2922b909938e087d0a14ad10998fcd/internal/notification/channels/smtp/channel.go#L151C2-L153C3

But there is 2 issues here (It seems to be introduced by [this PR](https://github.com/zitadel/zitadel/pull/6932)):
  - Web interface does not allow me to create a configuration with empty user and password (I don't know if it worked before)
![image](https://github.com/user-attachments/assets/783c7067-94bc-4d7a-8342-bd069eef0694)
 -  From API, It creates an SMTP config with a null password instead of an empty password which crash zitadel:

```python
 payload = json.dumps(
        {
            "senderAddress": "test@example.com",
            "senderName": "ZITADEL",
            "tls": True,
            "host": "relay.example.com:25",
            "user": "",
            "password": "",
            "replyToAddress": "",
            "description": "provider description",
        }
    )
```

```sql
          id         |         creation_date         |          change_date          | sequence |   resource_owner   |    instance_id     | tls |   sender_address    | sender_name | reply_to_address |         host         | username |                                             password                                             | state |     description
---------------------+-------------------------------+-------------------------------+----------+--------------------+--------------------+-----+---------------------+-------------+------------------+----------------------+----------+--------------------------------------------------------------------------------------------------+-------+-----------------------
  276668952849954883 | 2024-07-19 15:39:06.58709+00  | 2024-07-19 15:39:06.58709+00  |      118 | 276646757499156547 | 276646757499156547 |  t  | test@example.com    | ZITADEL     |                  | relay.example.com:25 |          | NULL                                                                                             |     3 | provider description
```

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xb9a0cf]

goroutine 5132 [running]:
github.com/zitadel/zitadel/internal/crypto.checkEncryptionAlgorithm(0x0, {0x56f7e10, 0xc002296990})
	/home/runner/work/zitadel/zitadel/internal/crypto/crypto.go:83 +0x2f
github.com/zitadel/zitadel/internal/crypto.DecryptString(0x0, {0x56f7e10, 0xc002296990})
	/home/runner/work/zitadel/zitadel/internal/crypto/crypto.go:76 +0x25
github.com/zitadel/zitadel/internal/command.(*Commands).TestSMTPConfigById(0xc00216b400, {0x56edbb8?, 0xc003e60ed0?}, {0xc003e2a7f8?, 0x2fc9d80?}, {0xc003e2a600?, 0xc003e6e900?}, {0xc003e12f90, 0x23})
	/home/runner/work/zitadel/zitadel/internal/command/smtp.go:345 +0x13b
github.com/zitadel/zitadel/internal/api/grpc/admin.(*Server).TestSMTPConfigById(0xc002a33e80, {0x56edbb8, 0xc003e60ed0}, 0xc003ed0ff0)
	/home/runner/work/zitadel/zitadel/internal/api/grpc/admin/smtp.go:134 +0xa6
github.com/zitadel/zitadel/pkg/grpc/admin._AdminService_TestSMTPConfigById_Handler.func1({0x56edbb8?, 0xc003e60ed0?}, {0x2e2bb60?, 0xc003ed0ff0?})
[...]
```

I've just pushed a commit on my [Zitadel repo](https://github.com/Etienne-gh/zitadel/commit/a7eecfc5b4377e36cea25ae7976c08fc5ff5b472) to fix the null password issue. It is working well for my needs but web interface still need to be fixed. And SMTP configuration updates should also handle empty password, and  I'm not sure how you want to handle the difference between the password is updated for an empty password and the password is not updated.

I'd be glad to continue working on this issue and create a PR if it seems relevant!

### To reproduce

```python
    url = "https://MYINSTANCE/admin/v1/smtp"

    payload = json.dumps(
        {
            "senderAddress": "test@example.com",
            "senderName": "ZITADEL",
            "tls": True,
            "host": "relay.example.com:25",
            "user": "",
            "password": "",
            "replyToAddress": "",
            "description": "provider description",
        }
    )
    headers = {
        "Content-Type": "application/json",
        "Accept": "application/json",
        "Authorization": "Bearer FIXME",
    }

    response = requests.request(
        "POST", url, headers=headers, data=payload, verify=False
    )

    print(response.text)
```

**Comment by jability** [comment]
Encountering this issue as well for an authless SMTP relay

**Comment by DoGab** [comment]
Same issue with newest version `v2.63.1`. If the TLS flag is set to `false` the UI but also API still requires a username/password. If you set a random username and no password it works to save the configuration and doesn't use TLS.

**Comment by peintnermax** [comment]
The required validator for user and password will be removed. Moved this to bugs/small issues, estimated about an hour

**Comment by cr1cr1** [comment]
Still present in `v2.67.4`. As a temporary workaround, use browser's developer tools to remove the `disabled` attribute from the Continue `<button` tag

**Comment by elinashoko** [comment]
Thanks for filing this issue. As part of an ongoing backlog cleanup, we're closing older `area/console` issues.

We're building a replacement for the Console with significantly better usability, and that's where our focus is right now. As a result, the current Console is planned for deprecation over the next 12 months, and we're not prioritizing fixes or improvements to it in the meantime.

If this is still an active problem for you, let us know in a comment (or reopen the issue) and we'll take another look.

This issue will close in 30 days if there's no further activity.
