### ISSUE TITLE
[Bug]: Crashes when using Unspecified NameID format while connecting with ADFS through SAML 2.0

### ISSUE THREAD

**Issue by tbhaxor** [zitadel/zitadel#8654]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

v2.61.0

### Database

PostgreSQL

### Database Version

16

### Describe the problem caused by this bug

<details>
<summary> Stack trace from Zitadel </summary>

<br />

```
2024/09/19 03:41:02 http: panic serving 10.2.6.234:5618: runtime error: invalid memory address or nil pointer dereference
goroutine 9050225 [running]:
net/http.(*conn).serve.func1()
        /opt/hostedtoolcache/go/1.22.6/x64/src/net/http/server.go:1903 +0xbe
panic({0x2d55160?, 0x7d7fc60?})
        /opt/hostedtoolcache/go/1.22.6/x64/src/runtime/panic.go:770 +0x132
github.com/zitadel/zitadel/internal/idp/providers/saml.(*Session).FetchUser(0xc0047bdef0, {0xc005da4390?, 0x2b?})
        /home/runner/work/zitadel/zitadel/internal/idp/providers/saml/session.go:76 +0x12d
github.com/zitadel/zitadel/internal/api/ui/login.(*Login).handleExternalLoginCallback(0xc001e38580, {0x5b7bd00, 0xc00573a320}, 0xc005e47680)
        /home/runner/work/zitadel/zitadel/internal/api/ui/login/external_provider_handler.go:336 +0xcb5
net/http.HandlerFunc.ServeHTTP(0xc0040d5860?, {0x5b7bd00?, 0xc00573a320?}, 0xc005e477a0?)
        /opt/hostedtoolcache/go/1.22.6/x64/src/net/http/server.go:2171 +0x29
github.com/zitadel/zitadel/internal/api/http/middleware.(*AccessInterceptor).Handle.(*AccessInterceptor).Handle.(*AccessInterceptor).handle.func1.func2({0x5b79a60, 0xc002ed2cc0}, 0xc005e47680)
        /home/runner/work/zitadel/zitadel/internal/api/http/middleware/access_interceptor.go:147 +0x1d2
net/http.HandlerFunc.ServeHTTP(0x5b80d38?, {0x5b79a60?, 0xc002ed2cc0?}, 0x5b28ad0?)
        /opt/hostedtoolcache/go/1.22.6/x64/src/net/http/server.go:2171 +0x29
github.com/zitadel/oidc/v3/pkg/op.(*IssuerInterceptor).setIssuerCtx(0x70?, {0x5b79a60, 0xc002ed2cc0}, 0xc005e47440, {0x5b33080, 0xc005d6ec00})
        /home/runner/go/pkg/mod/github.com/zitadel/oidc/v3@v3.28.1/pkg/op/context.go:52 +0x15a
github.com/zitadel/oidc/v3/pkg/op.(*IssuerInterceptor).Handler-fm.(*IssuerInterceptor).Handler.func1({0x5b79a60?, 0xc002ed2cc0?}, 0xc005e3f201?)
        /home/runner/go/pkg/mod/github.com/zitadel/oidc/v3@v3.28.1/pkg/op/context.go:28 +0x35
net/http.HandlerFunc.ServeHTTP(0xc005a06640?, {0x5b79a60?, 0xc002ed2cc0?}, 0xc006316d50?)
        /opt/hostedtoolcache/go/1.22.6/x64/src/net/http/server.go:2171 +0x29
github.com/zitadel/zitadel/internal/api/http/middleware.(*userAgentHandler).ServeHTTP(0xc006e4b810, {0x5b79a60, 0xc002ed2cc0}, 0xc005e47320)
        /home/runner/work/zitadel/zitadel/internal/api/http/middleware/user_agent_cookie.go:84 +0x23f
github.com/zitadel/zitadel/internal/api/http/middleware.(*headers).ServeHTTP(0xc005e3e3f0, {0x5b79a60, 0xc002ed2cc0}, 0xc005e47200)
        /home/runner/work/zitadel/zitadel/internal/api/http/middleware/security_headers.go:80 +0x7b9
github.com/zitadel/zitadel/internal/api/http/middleware.(*cacheInterceptor).Handler.func1({0x5b7fc90, 0xc005d333e0}, 0xc005e47200)
        /home/runner/work/zitadel/zitadel/internal/api/http/middleware/cache_interceptor.go:76 +0xaf
net/http.HandlerFunc.ServeHTTP(0xc00623b5c0?, {0x5b7fc90?, 0xc005d333e0?}, 0x2c2ba40?)
        /opt/hostedtoolcache/go/1.22.6/x64/src/net/http/server.go:2171 +0x29
github.com/zitadel/zitadel/internal/api/ui/login.CreateLogin.createCacheInterceptor.func3.1({0x5b7fc90, 0xc005d333e0}, 0xc005e47200)
        /home/runner/work/zitadel/zitadel/internal/api/ui/login/login.go:156 +0x10f
net/http.HandlerFunc.ServeHTTP(0x0?, {0x5b7fc90?, 0xc005d333e0?}, 0x4?)
        /opt/hostedtoolcache/go/1.22.6/x64/src/net/http/server.go:2171 +0x29
github.com/gorilla/csrf.(*csrf).ServeHTTP(0xc005d24d80, {0x5b7fc90, 0xc005d333e0}, 0xc005e46fc0)
        /home/runner/go/pkg/mod/github.com/gorilla/csrf@v1.7.2/csrf.go:306 +0x5a2
github.com/zitadel/zitadel/internal/api/ui/login.CreateLogin.createCSRFInterceptor.func2.1({0x5b7fc90, 0xc005d333e0}, 0xc005e46fc0)
        /home/runner/work/zitadel/zitadel/internal/api/ui/login/login.go:140 +0x370
net/http.HandlerFunc.ServeHTTP(0x0?, {0x5b7fc90?, 0xc005d333e0?}, 0x408296?)
        /opt/hostedtoolcache/go/1.22.6/x64/src/net/http/server.go:2171 +0x29
github.com/zitadel/zitadel/internal/api/http/middleware.(*instanceInterceptor).handleInstance(0xc002d2e440, {0x5b7fc90, 0xc005d333e0}, 0xc005e466c0, {0x5b33080, 0xc005e400e0})
        /home/runner/work/zitadel/zitadel/internal/api/http/middleware/instance_interceptor.go:69 +0x7b5
github.com/zitadel/zitadel/internal/api/http/middleware.(*instanceInterceptor).Handler-fm.(*instanceInterceptor).Handler.func1({0x5b7fc90?, 0xc005d333e0?}, 0x7ab1d01?)
        /home/runner/work/zitadel/zitadel/internal/api/http/middleware/instance_interceptor.go:38 +0x35
net/http.HandlerFunc.ServeHTTP(0x5b80d38?, {0x5b7fc90?, 0xc005d333e0?}, 0x7ab1d68?)
        /opt/hostedtoolcache/go/1.22.6/x64/src/net/http/server.go:2171 +0x29
github.com/zitadel/saml/pkg/provider.(*IssuerInterceptor).setIssuerCtx(0x120?, {0x5b7fc90, 0xc005d333e0}, 0xc005e465a0, {0x5b33080, 0xc0088bdc60})
        /home/runner/go/pkg/mod/github.com/zitadel/saml@v0.2.0/pkg/provider/context.go:51 +0x194
github.com/zitadel/saml/pkg/provider.(*IssuerInterceptor).Handler-fm.(*IssuerInterceptor).Handler.func1({0x5b7fc90?, 0xc005d333e0?}, 0x5b28a01?)
        /home/runner/go/pkg/mod/github.com/zitadel/saml@v0.2.0/pkg/provider/context.go:31 +0x35
net/http.HandlerFunc.ServeHTTP(0x5b80d38?, {0x5b7fc90?, 0xc005d333e0?}, 0x5b28ad0?)
        /opt/hostedtoolcache/go/1.22.6/x64/src/net/http/server.go:2171 +0x29
go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.(*middleware).serveHTTP(0xc005e302a0, {0x5b79e40, 0xc005e301c0}, 0xc005e46480, {0x5b33080, 0xc0088bdc80})
        /home/runner/go/pkg/mod/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.53.0/handler.go:218 +0x1086
go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.NewMiddleware.func1.1({0x5b79e40?, 0xc005e301c0?}, 0xc005e3e480?)
        /home/runner/go/pkg/mod/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.53.0/handler.go:74 +0x35
net/http.HandlerFunc.ServeHTTP(0xc005e46360?, {0x5b79e40?, 0xc005e301c0?}, 0x41ab18?)
        /opt/hostedtoolcache/go/1.22.6/x64/src/net/http/server.go:2171 +0x29
github.com/gorilla/mux.(*Router).ServeHTTP(0xc0030dbbc0, {0x5b79e40, 0xc005e301c0}, 0xc005e46240)
        /home/runner/go/pkg/mod/github.com/gorilla/mux@v1.8.1/mux.go:212 +0x1e2
github.com/zitadel/zitadel/internal/api.(*API).RegisterHandlerOnPrefix.StripPrefix.func1({0x5b79e40, 0xc005e301c0}, 0xc005e46120)
        /opt/hostedtoolcache/go/1.22.6/x64/src/net/http/server.go:2214 +0x262
net/http.HandlerFunc.ServeHTTP(0x3050720?, {0x5b79e40?, 0xc005e301c0?}, 0xc?)
        /opt/hostedtoolcache/go/1.22.6/x64/src/net/http/server.go:2171 +0x29
github.com/zitadel/zitadel/internal/api/http/middleware.RobotsTagHandler.func1({0x5b79e40, 0xc005e301c0}, 0xc005e46120)
        /home/runner/work/zitadel/zitadel/internal/api/http/middleware/robots_tag_interceptor.go:12 +0xf0
net/http.HandlerFunc.ServeHTTP(0xc005e46000?, {0x5b79e40?, 0xc005e301c0?}, 0x8?)
        /opt/hostedtoolcache/go/1.22.6/x64/src/net/http/server.go:2171 +0x29
github.com/zitadel/zitadel/cmd/start.startAPIs.WithOrigin.func1.1({0x5b79e40, 0xc005e301c0}, 0xc005e46000)
        /home/runner/work/zitadel/zitadel/internal/api/http/middleware/origin_interceptor.go:23 +0x28b
net/http.HandlerFunc.ServeHTTP(0xc005d7fe60?, {0x5b79e40?, 0xc005e301c0?}, 0xc005f62ab0?)
        /opt/hostedtoolcache/go/1.22.6/x64/src/net/http/server.go:2171 +0x29
github.com/gorilla/mux.(*Router).ServeHTTP(0xc0030da780, {0x5b79e40, 0xc005e301c0}, 0xc005d7fd40)
        /home/runner/go/pkg/mod/github.com/gorilla/mux@v1.8.1/mux.go:212 +0x1e2
golang.org/x/net/http2/h2c.h2cHandler.ServeHTTP({{0x5b32f20?, 0xc0030da780?}, 0xc00198ee40?}, {0x5b79e40, 0xc005e301c0}, 0xc005d7fd40)
        /home/runner/go/pkg/mod/golang.org/x/net@v0.26.0/http2/h2c/h2c.go:125 +0x697
net/http.serverHandler.ServeHTTP({0xc0055f94d0?}, {0x5b79e40?, 0xc005e301c0?}, 0x6?)
        /opt/hostedtoolcache/go/1.22.6/x64/src/net/http/server.go:3142 +0x8e
net/http.(*conn).serve(0xc0059cbdd0, {0x5b80d38, 0xc0019ab1a0})
        /opt/hostedtoolcache/go/1.22.6/x64/src/net/http/server.go:2044 +0x5e8
created by net/http.(*Server).Serve in goroutine 3331
        /opt/hostedtoolcache/go/1.22.6/x64/src/net/http/server.go:3290 +0x4b4
```

</details>

<details>
<summary>Error message from Windows Event Viewer</summary>

<br />

```
Exception details: 
Microsoft.IdentityServer.Protocols.Saml.InvalidNameIdPolicyException: MSIS7070: The SAML request contained a NameIDPolicy that was not satisfied by the issued token. Requested NameIDPolicy: AllowCreate: True Format: urn:oasis:names:tc:SAML:2.0:nameid-format:persistent SPNameQualifier: . Actual NameID properties: null.
   at Microsoft.IdentityServer.Web.Protocols.Saml.SamlProtocolManager.Issue(HttpSamlRequestMessage httpSamlRequestMessage, SecurityTokenElement onBehalfOf, String sessionState, String relayState, String& newSamlSession, String& samlpAuthenticationProvider, Boolean isUrlTranslationNeeded, WrappedHttpListenerContext context, Boolean isKmsiRequested)
   at Microsoft.IdentityServer.Web.Protocols.Saml.SamlProtocolHandler.RequestBearerToken(WrappedHttpListenerContext context, HttpSamlRequestMessage httpSamlRequest, SecurityTokenElement onBehalfOf, String relyingPartyIdentifier, Boolean isKmsiRequested, Boolean isApplicationProxyTokenRequired, String& samlpSessionState, String& samlpAuthenticationProvider)
   at Microsoft.IdentityServer.Web.Protocols.Saml.SamlProtocolHandler.BuildSignInResponseCoreWithSerializedToken(HttpSamlRequestMessage httpSamlRequest, WrappedHttpListenerContext context, String relyingPartyIdentifier, SecurityTokenElement signOnTokenElement, Boolean isKmsiRequested, Boolean isApplicationProxyTokenRequired)
   at Microsoft.IdentityServer.Web.Protocols.Saml.SamlProtocolHandler.BuildSignInResponseCoreWithSecurityToken(SamlSignInContext context, SecurityToken securityToken, SecurityToken deviceSecurityToken)
   at Microsoft.IdentityServer.Web.Protocols.Saml.SamlProtocolHandler.Process(ProtocolContext context)
   at Microsoft.IdentityServer.Web.PassiveProtocolListener.ProcessProtocolRequest(ProtocolContext protocolContext, PassiveProtocolHandler protocolHandler)
   at Microsoft.IdentityServer.Web.PassiveProtocolListener.OnGetContext(WrappedHttpListenerContext context)
```

</details>

### To reproduce

1. Spin up MS Server 2016
2. Add AD DS, AD FS and AD CS componenets
3. Create SAML provider in the Zitadel
4. Download and install the metadata in the relying trusted party
5. Change the signing algorithm to sha1 (why required, [check here](https://discord.com/channels/927474939156643850/1285939724808355880))
6. By default NameID is unspecified from ADFS, so choose the same in Zitadel

### Operating System

Linux, through Docker

### Relevant Configuration

Although we have solved it using by mapping `User-Principal-Name` from active directory domain to `Name ID` claim in the SAML. But it shouldn't crash the zitadel at any point.

**Comment by fforootd** [comment]
Relates to https://discord.com/channels/927474939156643850/1019895518383583323/threads/1286171466097885204

Mabye intersting for @stebenz
